### ISSUE TITLE
csv download error

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#213]
testing on safari with new version of authoring tool (on safari) the csv export appears to be failing. 
download.csv.json file contains {"msg": "'editor'", "error": 1

Note JSON does appear to be working.

**Comment by benismobile** [comment]
and KML working too.

**Comment by gmh04** [comment]
Can't get hold of Ruben to do a release of the pcapi, so this has been hotfixed on rainbow for you to try.

**Comment by benismobile** [comment]
have tested this and confirm working for my dataset

**Comment by benismobile** [comment]
this seems to have cropped up again after Panos made latest release to migration script - maybe George's hotfix got overwritten?

**Comment by gmh04** [comment]
Yes it has, see line 735 of .local/lib/python2.6/site-packages/pcapi/rest.py, yet the change has clearly been committed https://github.com/edina/pcapi/commit/846a711906034d3a59364d835c4835f586d9a44a to source control.  The problem here is there is no automated or documented way of deploying the pcapi, see https://github.com/edina/fieldtrip-gb/issues/193.  From what I have seen the app is being deployed in different ways depending on who is doing the deploy, its why I don't do deploys of the pcapi (or the authoring tool) preferring to allow one person to do it, at least hoping for some consistency.

**Comment by panterz** [comment]
I've deployed the latest pcapi on rainbow and all the latest changes there.
