### ISSUE TITLE
First time log in through web browser

### ISSUE THREAD

**Issue by jollopre** [edina/fieldtrip-gb#253]
The first time trying to log in through the authoring tool I receive the following error:

"Something went wrong with your synching. Please try again!

If the first time log in it through a mobile this error does not appear. Apparently, the folder for the app is empty (without records) after using the browser.

**Comment by rgamez** [comment]
In order to reproduce it:
1. Go to https://www.dropbox.com/account#security and remove the autorization for FieldtripGB
2. Go to the authoring tool and login

Workarounds:
After authorizing the authoring tool create the  /records  directory manually or upload a record using the app, this will force to create the missing records directory.

**Comment by rgamez** [comment]
The directories are never created because the creation relays in a call to [exists(path)](https://github.com/edina/pcapi/blob/f077a3ffc63664aafbce70f29b4b53a9b3663b61/src/pcapi/dbox_provider.py#L252) which is not implemented for the Dropbox provider (it is returning True always)
